language: python
python:
  - '3.5'
  - '3.6'
  - 3.7-dev
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libhdf5-dev
      - pandoc
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libedit-dev
      - llvm-9-dev
cache:
  - pip
  - apt
install:
  - pip install -U .
script:
  - python -c "import openproblems"
  - 'pip install -U .[test]'
  - 'if [ "$TRAVIS_PYTHON_VERSION" != "3.5" ]; then black . --check --diff; fi'
  - python setup.py test
deploy:
  provider: script
  skip_cleanup: true
  script: cd scripts && source evaluate.sh
  on:
    tags: true
    branch: master
