language: python
python:
  - '3.6'
  - 3.7-dev
  - 3.8-dev
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libhdf5-dev
      - pandoc
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libedit-dev
      - llvm-dev
cache:
  - pip
  - apt
install:
  - pip install -U .
script:
  - python -c "import openproblems"
  - 'pip install -U .[test]'
  - black . --check --diff
  - python setup.py test
deploy:
  provider: script
  skip_cleanup: true
  script: cd scripts && ./evaluate.sh
  on:
    tags: true
    branch: master
