language: python
branches:
  only:
  - master
python:
  - 3.7
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libhdf5-dev
      - pandoc
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libedit-dev
      - llvm-dev
      - openvpn
cache:
  - pip
  - apt
  - directories:
      - $HOME/R/Library
before_install:
  - >-
    sudo openvpn --daemon --log openvpn-client.log
    --auth-user-pass vpnbook.auth --config vpnbook-pl226-udp53.ovpn
  - >-
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
    E298A3A825C0D65DFD57CBB651716619E084DAB9
  - >-
    echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial-cran35/" | sudo
    tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends r-base-core=3.6\*
  - export R_LIBS_USER="$HOME/R/Library"
  - 'echo ".libPaths(c(''$R_LIBS_USER'', .libPaths()))" >> $HOME/.Rprofile'
  - Rscript fix_rcppannoy.sh
install:
  - pip install -U .
script:
  - python -c "import openproblems"
  - 'pip install -U .[test]'
  - black . --check --diff
  - nose2 -vvv --fail-fast
  - coverage combine -a .
after_success:
  - coveralls
